# This file describes the keymaps that will be built by the GitHub Actions CI.

include:

  # Quacken Zero + SparkFun RP2040
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: quacken_zero
    artifact-name: quacken_zero
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DCONFIG_ZMK_STUDIO=y

  # Quacken Flex
  - board: quacken_flex
    artifact-name: quacken_flex
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DCONFIG_ZMK_STUDIO=y

    # Quacken Flex, Ergol + Vim + hrm_shift config
  - board: quacken_flex
    artifact-name: quacken_flex_ergol_vim_shift
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DVIM_NAVIGATION;-DHRM_SHIFT"
      -DCONFIG_ZMK_STUDIO=y

    # Quacken Flex, Ergol + Vim + 2tk config
  - board: quacken_flex
    artifact-name: quacken_flex_ergol_2tk
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DVIM_NAVIGATION;-DHT_TWO_THUMB_KEYS"
      -DCONFIG_ZMK_STUDIO=y

    # Quacken Flex, Azerty + thumb-taps config
  - board: quacken_flex
    artifact-name: quacken_flex_azerty_tt
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_AZERTY;-DHT_THUMB_TAPS"
      -DCONFIG_ZMK_STUDIO=y

    # Quacken Flex, Ergol + Hummingbird config
  - board: quacken_flex
    artifact-name: quacken_flex_ergol_hummingbird
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DHUMMINGBIRD"
      -DCONFIG_ZMK_STUDIO=y
      
    # Quacken Flex, Ergoflan
  - board: quacken_flex
    artifact-name: quacken_flex_ergoflan
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-keyboard-quacken/zmk-keyboard-quacken/keymaps/quacken.keymap
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOFLAN"
      -DCONFIG_ZMK_STUDIO=y

